-- Profiles (Characters) table
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  username TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  character_class TEXT,
  bio TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Channels table
CREATE TABLE channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  creator_id UUID REFERENCES profiles(id),
  privacy TEXT CHECK (privacy IN ('public', 'private', 'unlisted')) DEFAULT 'public',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Messages table
CREATE TABLE messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES profiles(id),
  channel_id UUID REFERENCES channels(id) NOT NULL,
  content TEXT,
  message_type TEXT CHECK (message_type IN ('chat', 'action', 'dice_roll', 'system')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Channel memberships table (for private channels)
CREATE TABLE channel_memberships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id),
  role TEXT CHECK (role IN ('member', 'moderator', 'admin')) DEFAULT 'member',
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(channel_id, user_id)
);

-- Followers table
CREATE TABLE followers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  follower_id UUID REFERENCES profiles(id),
  following_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

-- Reactions table (Energy system)
CREATE TABLE reactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES profiles(id),
  message_id BIGINT REFERENCES messages(id),
  reaction_type TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS channels_creator_idx ON channels(creator_id);
CREATE INDEX IF NOT EXISTS channels_privacy_idx ON channels(privacy);
CREATE INDEX IF NOT EXISTS channels_created_at_idx ON channels(created_at);
CREATE INDEX IF NOT EXISTS messages_channel_idx ON messages(channel_id);
CREATE INDEX IF NOT EXISTS channel_memberships_channel_idx ON channel_memberships(channel_id);
CREATE INDEX IF NOT EXISTS channel_memberships_user_idx ON channel_memberships(user_id);
CREATE INDEX IF NOT EXISTS channel_memberships_role_idx ON channel_memberships(role);
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON messages (created_at);
CREATE INDEX IF NOT EXISTS followers_follower_id_idx ON followers (follower_id);
CREATE INDEX IF NOT EXISTS followers_following_id_idx ON followers (following_id);
CREATE INDEX IF NOT EXISTS reactions_message_id_idx ON reactions (message_id);

