-- Profiles (Characters) table
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  username TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  character_class TEXT,
  bio TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Messages table
CREATE TABLE messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES profiles(id),
  content TEXT,
  message_type TEXT CHECK (message_type IN ('chat', 'action', 'dice_roll', 'system')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Followers table
CREATE TABLE followers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  follower_id UUID REFERENCES profiles(id),
  following_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

-- Reactions table (Energy system)
CREATE TABLE reactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES profiles(id),
  message_id BIGINT REFERENCES messages(id),
  reaction_type TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON messages (created_at);
CREATE INDEX IF NOT EXISTS followers_follower_id_idx ON followers (follower_id);
CREATE INDEX IF NOT EXISTS followers_following_id_idx ON followers (following_id);
CREATE INDEX IF NOT EXISTS reactions_message_id_idx ON reactions (message_id);